#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if command -v brew &> /dev/null; then
  if [[ -s `brew --prefix`/share/chruby/chruby.sh ]]; then
    source `brew --prefix`/share/chruby/chruby.sh
    # source `brew --prefix`/share/chruby/auto.sh
    chruby ruby
  fi
fi

if command -v direnv &> /dev/null; then
  eval "$(direnv hook zsh)"
fi
